class ERD {
  static const APPLIANCE_MODEL_NUMBER = "0x0001";
  static const TOASTER_OVEN_CURRENT_STATE = "0x9209";
  static const TOASTER_OVEN_CANCEL_OPERATION = "0x9228";
  static const TOASTER_OVEN_COOK_TIME_REMAINING = "0x922f";
  static const STAND_MIXER_MODE_STATE = "0x9300";
  static const STAND_MIXER_CONTROL_CURRENT_SETTINGS = "0x9301";
  static const STAND_MIXER_CONTROL_REQUESTED_SETTINGS = "0x9302";
  static const STAND_MIXER_CONTROL_SETTINGS_LIMITS = "0x9303";
  static const STAND_MIXER_PAUSE_MIXING_CYCLE = "0x9304";
  static const STAND_MIXER_STATE = "0x9305";
  static const STAND_MIXER_NOTIFICATIONS = "0x9306";
  static const STAND_MIXER_RESET_CHECK_CALIBRATION_FLAG = "0x9307";
  static const STAND_MIXER_RUN_TIME_IN_MINUTES = "0x9308";
  static const STAND_MIXER_CYCLE_SETTING_MODIFICATION_AVAILABILITY = "0x9309";
  static const STAND_MIXER_CYCLE_TIMER_ABSOLUTE_TIME_MODIFICATION = "0x930f";
  static const STAND_MIXER_SCALE_DISPLAY_CURRENT_UNITS = "0x930b";
  static const STAND_MIXER_SCALE_DISPLAY_REQUESTED_UNITS = "0x930c";
  static const STAND_MIXER_SCALE_CURRENT_TARGET_WEIGHT = "0x930d";
  static const STAND_MIXER_SCALE_REQUESTED_TARGET_WEIGHT = "0x930e";
  static const STAND_MIXER_SCALE_DISPLAY_ENABLE = "0x930f";
  static const STAND_MIXER_TARE_SCALE = "0x9310";
  static const STAND_MIXER_SCALE_ACTION_AVAILABILITY = "0x9311";
  static const STAND_MIXER_SUPPORTED_EQUIPMENT = "0x9312";
  static const RECIPE_STATUS = "0x5300";
  static const APPLIANCE_BRAND_TYPE = "0x0099";
}
